resources:
- name: gitBugTest
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$
- name: jfrog_xray_java_client_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: master
- name: parent_pom_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$
    files:
      include: \bparent-pom\/.+\b
- name: commons_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$
    files:
      include: \bcommons(-pro)?\/.+\b
- name: metadata_java_client_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$
    files:
      include: \bmetadata-java-client\/.+\b
- name: access_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$
    files:
      include: \baccess(-pro)?\/.+\b
- name: package_indexer_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$
    files:
      include: \bpackage-indexer\/.+\b
- name: binary_store_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$
    files:
      include: \bbinary-store(-pro)?\/.+\b
- name: artifactory_oss_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$
    files:
      include: \bartifactory-oss\/.+\b
- name: artifactory_pro_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$
    files:
      include: \bartifactory-pro\/.+\b
- name: distribution_bitbucket
  type: GitRepo
  configuration:
    path: ChaitanyaVootla/ymlTest
    gitProvider: gitBugTest
    branches:
      include: ^{{gitBranch}}$

pipelines:
- name: jfrog_build
  steps:
  - name: package_indexer
    type: Bash
    configuration:
      inputResources:
        - name: package_indexer_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: parent_pom
    type: Bash
    configuration:
      inputResources:
        - name: parent_pom_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: commons
    type: Bash
    configuration:
      inputSteps:
        - name: parent_pom
      inputResources:
        - name: commons_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: jfrog_xray_java_client
    type: Bash
    configuration:
      inputSteps:
        - name: commons
      inputResources:
        - name: jfrog_xray_java_client_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: metadata_java_client
    type: Bash
    configuration:
      inputSteps:
      - name: commons
      inputResources:
        - name: metadata_java_client_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: commons_pro
    type: Bash
    configuration:
      inputSteps:
        - name: commons
      inputResources:
        - name: commons_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: access
    type: Bash
    configuration:
      inputSteps:
        - name: commons_pro
      inputResources:
        - name: access_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: access_pro
    type: Bash
    configuration:
      inputSteps:
        - name: access
      inputResources:
        - name: access_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: binarystore
    type: Bash
    configuration:
      inputSteps:
        - name: access_pro
      inputResources:
        - name: binary_store_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: binarystore_pro
    type: Bash
    configuration:
      inputSteps:
        - name: binarystore
      inputResources:
        - name: binary_store_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: artifactory_oss
    type: Bash
    configuration:
      inputSteps:
        - name: binarystore_pro
        - name: metadata_java_client
      inputResources:
        - name: artifactory_oss_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: artifactory_pro
    type: Bash
    configuration:
      inputSteps:
        - name: artifactory_oss
        - name: package_indexer
        - name: jfrog_xray_java_client
      inputResources:
        - name: artifactory_pro_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'
  - name: distribution
    type: Bash
    configuration:
      inputSteps:
        - name: access
        - name: jfrog_xray_java_client
      inputResources:
        - name: distribution_bitbucket
          trigger: true
    execution:
      onExecute:
        - echo 'done'